require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JokeContentsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # JokeContent. As you add validations to JokeContent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JokeContentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all joke_contents as @joke_contents" do
      joke_content = JokeContent.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:joke_contents)).to eq([joke_content])
    end
  end

  describe "GET show" do
    it "assigns the requested joke_content as @joke_content" do
      joke_content = JokeContent.create! valid_attributes
      get :show, {:id => joke_content.to_param}, valid_session
      expect(assigns(:joke_content)).to eq(joke_content)
    end
  end

  describe "GET new" do
    it "assigns a new joke_content as @joke_content" do
      get :new, {}, valid_session
      expect(assigns(:joke_content)).to be_a_new(JokeContent)
    end
  end

  describe "GET edit" do
    it "assigns the requested joke_content as @joke_content" do
      joke_content = JokeContent.create! valid_attributes
      get :edit, {:id => joke_content.to_param}, valid_session
      expect(assigns(:joke_content)).to eq(joke_content)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new JokeContent" do
        expect {
          post :create, {:joke_content => valid_attributes}, valid_session
        }.to change(JokeContent, :count).by(1)
      end

      it "assigns a newly created joke_content as @joke_content" do
        post :create, {:joke_content => valid_attributes}, valid_session
        expect(assigns(:joke_content)).to be_a(JokeContent)
        expect(assigns(:joke_content)).to be_persisted
      end

      it "redirects to the created joke_content" do
        post :create, {:joke_content => valid_attributes}, valid_session
        expect(response).to redirect_to(JokeContent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved joke_content as @joke_content" do
        post :create, {:joke_content => invalid_attributes}, valid_session
        expect(assigns(:joke_content)).to be_a_new(JokeContent)
      end

      it "re-renders the 'new' template" do
        post :create, {:joke_content => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested joke_content" do
        joke_content = JokeContent.create! valid_attributes
        put :update, {:id => joke_content.to_param, :joke_content => new_attributes}, valid_session
        joke_content.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested joke_content as @joke_content" do
        joke_content = JokeContent.create! valid_attributes
        put :update, {:id => joke_content.to_param, :joke_content => valid_attributes}, valid_session
        expect(assigns(:joke_content)).to eq(joke_content)
      end

      it "redirects to the joke_content" do
        joke_content = JokeContent.create! valid_attributes
        put :update, {:id => joke_content.to_param, :joke_content => valid_attributes}, valid_session
        expect(response).to redirect_to(joke_content)
      end
    end

    describe "with invalid params" do
      it "assigns the joke_content as @joke_content" do
        joke_content = JokeContent.create! valid_attributes
        put :update, {:id => joke_content.to_param, :joke_content => invalid_attributes}, valid_session
        expect(assigns(:joke_content)).to eq(joke_content)
      end

      it "re-renders the 'edit' template" do
        joke_content = JokeContent.create! valid_attributes
        put :update, {:id => joke_content.to_param, :joke_content => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested joke_content" do
      joke_content = JokeContent.create! valid_attributes
      expect {
        delete :destroy, {:id => joke_content.to_param}, valid_session
      }.to change(JokeContent, :count).by(-1)
    end

    it "redirects to the joke_contents list" do
      joke_content = JokeContent.create! valid_attributes
      delete :destroy, {:id => joke_content.to_param}, valid_session
      expect(response).to redirect_to(joke_contents_url)
    end
  end

end
